[package]
name = "bepl_t3x16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.21"
env_logger = "0.11.3"
cli-clipboard = "0.4.0"
mc_schem = "1.1.2"
